### ISSUE TITLE
Clean up `libs` folder.

### ISSUE THREAD

**Issue by markulf** [mitls/mitls-fstar#1]
Title says it all. General purpose libraries have been moved to https://github.com/FStarLang/FStar/tree/master/contrib.

**Comment by beurdouche** [comment]
I think we should simply delete this folder, it is more confusing than useful...

**Comment by markulf** [comment]
@s-zanella @karthikbhargavan still anything useful in here? Otherwise I would delete it.

**Comment by s-zanella** [comment]
I believe we are not using anything in that folder now. It's fine to remove CoreCrypto and Platform now, but there are bits that we want to keep for later (e.g. the standalone DHDBManager). I can recover the code from somewhere else if need be, but I don't see the urge to delete everything.

**Comment by markulf** [comment]
ok, deleted deprecated folders only. What about the fs/ folder?

**Comment by s-zanella** [comment]
That folder contains the bulk of DHDBManager, so don't delete at least the DHDBManager subfolder.
