### ISSUE TITLE
Unit tests for CoreCrypto

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#10]
Wrappers around OpenSSL
    Current status: Mostly done. 
    Lots of tests for AES_GCM, AES_CBC, HMAC, SHA*, ECC, ECDHE, FFDHE
    More interop tests for signatures needed (i.e. right now a dummy implementation would pass these tests -- need to check that the actual bytes are correct)
    Specifically, we need test vectors for TestRsa, TestDsa, TestEcdsa
    Plenty of vectors we can borrow from OpenSSL (already using them for CBC and GCM)
    Need to move stuff out of TLSConstants.fst and move it into CoreCrypto.fst (coordinate)
    
Sign-off criteria: test vectors for any crypto we implement in CoreCrypto.

**Comment by s-zanella** [comment]
- [ ] Test vectors for point EC membership
- [ ] Test vectors for FFDHE and ECDHE
- [ ] Test vectors fro RSA, DSA and ECDSA signatures
- [ ] Test vectors for AES_GCM
- [ ] Test vectors for AES_CBC
- [ ] Test vectors for HMAC
- [ ] Test vectors for SHA1, SHA256, SHA384

**Comment by msprotz** [comment]
@ad-l says we don't care about DSA and he added tests for RSA and ECDSA

**Comment by sishtiaq** [comment]
I can help!

**Comment by s-zanella** [comment]
This should be lower priority now that we have good coverage of most functions in CoreCrypto.fst.
However, it'd be good to have more tests anticipating the moment when we start supporting a backend other than OpenSSL.
