### ISSUE TITLE
Implementation of AES GCM in Dafny/Spartan

### ISSUE THREAD

**Issue by vkanne-msft** [mitls/mitls-fstar#107]
This is about extracting AES GCM, written in Spartan, through Dafny+Kremlin, as a C file.

The extended goal is to expose OCaml bindings for these, possibly through ocaml-ctypes, so that we can rig CoreCrypto to use this implementation. (Ideally, configurable at run-time for benchmarks.)

**Comment by msprotz** [comment]
This is about extracting AES GCM, written in Spartan, through Dafny+Kremlin, as a C file.

The extended goal is to expose OCaml bindings for these, possibly through ocaml-ctypes, so that we can rig CoreCrypto to use this implementation. (Ideally, configurable at run-time for benchmarks.)

**Comment by vkanne-msft** [comment]
- [ ] AES is done 
- [ ] AES- CBC and HMAC is in progress 
- [ ] GCM is not yet complete- Will punt to M2

**Comment by BarryBo** [comment]
Closing as old/stale.  The new Vale/F* AES-GCM-128 for AMD64 is in the tree now.
