### ISSUE TITLE
Integrate Curve25519 code form Hacl*

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#11]
Where is it today?
Can we add it to the F\* regression suite?
Perhaps a separate project/sub-module on github

**Comment by s-zanella** [comment]
We should extend `LowCProvider` to be able to call into Hacl* code for curve25519. 
This will be integrated into mitls-fstar once we unify the memory models.

**Comment by BarryBo** [comment]
Closing.  Done long ago.
