### ISSUE TITLE
C extraction from Dafny for SHA, AES and RSA

### ISSUE THREAD

**Issue by vkanne-msft** [mitls/mitls-fstar#112]
Work required to extract two crypto algorithms written in Dafny to C. #108 #107 #106

**Comment by BarryBo** [comment]
Current status:
- blocked waiting on Kremlin work (user-defined types, change to EBufAlloc, while loops and return statements)
- SHA256 generates mostly plausible JSON input to Kremlin.  Once the blockers are implemented, we'll see C code-gen for the first time.
- I haven't started on AES or RSA.
- I'm working with Rustan to create a private branch of Dafny, for my changes to sit in until they are ready for broad consumption

**Comment by BarryBo** [comment]
Making progress. Blocked until Kremlin supports mutable UDTs.
Changes are now committed in a branch of the branch of Dafny used for Spartan.

**Comment by BarryBo** [comment]
SHA256 - extracted and working
AES - extracted and working
RSA - no Dafny/Spartan implementation yet, so no progress

**Comment by vkanne-msft** [comment]
@BarryBo can we close this and create a new one for RSA ?

**Comment by BarryBo** [comment]
Go ahead and create one for RSA.  We are still working through AES issues.  I hope to close it out later today.
