### ISSUE TITLE
Remove preprocessor

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#12]
We will get rid of the pre-processor for good
Instead, we will use language-level conditionals

Roughly:
    We type-check the program w.r.t an abstract predicate safeId: id -> Tot bool
    Concretely, the predicate is always false

How to get extraction to be smart enough to get rid of ideal stuff, unused concretely?
Maybe switch to use options everywhere for logs, for example.

Plan:
    For now, we go with language-level conditionals instead of #ideal
    Later, we improve extraction to erase ideal branches and allocations

**Comment by s-zanella** [comment]
Files currently needing pre-processing:
- [ ] PMS.fst
- [ ] Sig.fst
- [ ] PRF.fst

**Comment by markulf** [comment]
Nonce uses an ideal flag, tie that into SafeId? https://github.com/mitls/mitls-fstar/issues/16

**Comment by markulf** [comment]
A design I discussed with Santiago is to have one `ideal` flag for every module, or even different aspects of modules that are idealized.

For verification we assume all these flags as 
`assume val ideal_Nonce : bool` 
`assume val ideal_Sig : bool`
`assume val ideal_PRF bool`
in a file called `Ideal.fst`

For compilation we set all these flags to false in a file called `Concrete.fst`.
For verification and extraction respectively we copy `Ideal.fst` and `Concrete.fst` to a file called `IdealFlags.fst` and include it as a module.

**Comment by markulf** [comment]
We did not verify any ideal code. Consequently, some of the old code did not type check. 

In particular, honesty predicates of the form 
```let honest (pk:pk): bool = failwith "only used in ideal implementation, unverified"```
had the wrong effect. Currently set to `let honest (pk:pk): bool = false`, but preferably we would have a *stateful* implementation when idealizing?

**Comment by markulf** [comment]
These files also still had `#verify` flags. As I understand it these flags primarily documented the state of F7 verification and are obsolete.

I removed `#ideal` from PMS.fst, and simplified `Sig.fst` and `PRF.fst`. To completely remove `#ideal` we need proper stateful implementations of the idealization logs.

**Comment by msprotz** [comment]
discussed in the meeting -- Nik showed how to deal with it in a sample file, ongoing

**Comment by msprotz** [comment]
@fournet: "how does it affect verification style"

**Comment by ad-l** [comment]
I think PRF was the last one, so this is complete right?
