### ISSUE TITLE
Implement ciphersuite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#13]
Running one ciphersuite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
a. Ciphersuite: 
    i. RSA: not done yet, dummy implementation. No signing yet either.
    ii. ECDHE, AES128, GCM, SHA256 done.
b. First TLS 1.2. , then TLS 1.3 (1-RTT), then TLS 1.3 0-RTT. 
c. As client + server in the same program (intermediate step with idealization, may be skipped)
d. As client + server on their own
e. Interop.
f. Similarly, pick some existing tests somewhere.

**Comment by ad-l** [comment]
Ever
