### ISSUE TITLE
Functional correctness of ChaCha20, Poly1305

### ISSUE THREAD

**Issue by vkanne-msft** [mitls/mitls-fstar#131]
Goal : To verify we have a functionally correct implementations of ChaCha20, Poly1305. This task has an overlap with #83.

**Comment by sishtiaq** [comment]
@ad-l: I can/would_like_to help with one of these, if you give me guidance from the other one.

**Comment by s-zanella** [comment]
I thought that we agreed on assigning this one to me during the meeting.
I've been working on this for the past days. I'm not too far from fully verifying Poly1305. There's not much to do for ChaCha20 either. 

@sishtiaq: I can leave leave some unproved lemmas or assumes for you to prove if you wish. If you want to give it a go now, I still haven't proved `lemma_toField_1 .. 3` in `Crypto.Symmetric.Poly1305.fst`.

**Comment by sishtiaq** [comment]
Thanks, @s-zanella, will have a look on Mon. I might bug you for help in helping me!

**Comment by s-zanella** [comment]
This is complete now in the `c_record_aead` branch of `fstar`.
 See e.g. `examples/low-level/crypto/Crypto.Symmetric.Poly1305.Standalone.fst`
No assumes/admits left, the code is extracting to OCaml and C, and tests are passing.
