### ISSUE TITLE
PRF, MAC, and AEAD idealization 

### ISSUE THREAD

**Issue by vkanne-msft** [mitls/mitls-fstar#133]
@ad-l @markulf , Please add a detailed description. 

Goal : As part of the goal to have a fully verified Record layer we idealize AEAD constructions.

For the counter-mode based AEAD schemes AES-GCM and ChaCha-Poly, this involves idealizing a PRF and a Wegman-Carter-Shoup MAC.
- [x] Idealize PRF for MAC key generation
- [x] Idealize Wegman-Carter-Shoup MAC
- [x] Idealize PRF for Encryption and Decryption

**Comment by markulf** [comment]
A lot of progress was made and @ad-l and I were not the only involved. Verification is still ongoing, and we also became more ambitious aiming at a full integration of AES-GCM within the same codebase.

**Comment by s-zanella** [comment]
Done in `hacl_star`
