### ISSUE TITLE
Support ALPN (Application Layer Protocol Negotation)

### ISSUE THREAD

**Issue by BarryBo** [mitls/mitls-fstar#136]
This is an extension to the ClientHello message that enables clients to request HTTP/2 and other custom protocols on top of TLS.

It is needed for schannel feature parity.

From slack:

> **Barry Bond [5:50 AM]**  
> Does miTLS support ALPN (Application Layer Protocol Negotiation)?  This is an extension to the ClientHello message.
> 
> **Santiago Zanella-Béguelin [6:57 AM]**  
> It doesn't. It won't be hard to add, I think.
> 
> Karthikeyan Bhargavan [7:49 AM]  
> It will be easy; we have the extension coded up somewhere.
> 
> new messages
> 
> ----- Today October 3rd, 2016 -----
> **Antoine Delignat-Lavaud [4:55 AM]**  
> there is parser support but it is not negotiated

**Comment by s-zanella** [comment]
@ad-l implemented this recently. It's configurable using `FFI.ffiSetALPN`.
