### ISSUE TITLE
App Integration/Deployment

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#143]
Epic for integration of Everest into applications.

**Comment by BarryBo** [comment]
@sishtiaq can you please expand this with specifics - issue 129 tracks the M1 work for curl.

**Comment by sishtiaq** [comment]
@BarryBo Are there other apps/deployments that we are looking into for Milestone 1 too? If not, then I'll close this umbrella epic for such work.

**Comment by BarryBo** [comment]
No, there are no others planned for M1.
