### ISSUE TITLE
Crypto integration between miTLS and Spartan/Dafny extracted code 

### ISSUE THREAD

**Issue by vkanne-msft** [mitls/mitls-fstar#146]
We’ll have to think through how miTLS discovers crypto algorithms and how to specify them from the host app.  This impacts all of the potential crypto providers into miTLS…. We need a verified equivalent to libcrypto.
For M1 we will make unverified calls into crypto

**Comment by BarryBo** [comment]
This has high overlap with issue 145 both in M1, where miTLS's interface to crypto is changing, and beyond.

I'll use this to track simply plugging the Spartan code into OpenSSL libcrypto so that miTLS can invoke it through its current unverified callouts to OpenSSL.
