### ISSUE TITLE
Implement Extensions

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#163]
Work item for 1.3 Extensions. 

- [x] Define data type.
- [x] Define parsing and serializing functions. Write tests for them. Prove them inverse. 
  ```
  extensionBytes  : extension -> Tot bytes 
  parseExtensions : bytes -> Tot (list extension) 
  ```
- [x] Define prepareExtensions: 
  ```
  prepareExtensions : config -> extensions
  ```
  for Nego.

**Comment by s-zanella** [comment]
Done for mandatory extensions. Closing.
