### ISSUE TITLE
Support NPN Application Extension

### ISSUE THREAD

**Issue by BarryBo** [mitls/mitls-fstar#171]
This is fairly low priority.  

On Windows, wininet.dll sends ALPN by default, and only sends NPN if HKEY_CURRENT_USER\Internet Explorer\EnableNpn is set in the registry.  I don't see this in use in other schannel applications.

Curl supports it via curl_easy_setopt(curl, CURLOPT_SSL_ENABLE_NPN, 1L);.  I believe the command line curl passes ALPN and NPN both by default, as --no-alpn and --np-npn disable them.

**Comment by ad-l** [comment]
NPN is mostly dead at this point, I think it is reasonable to stick to ALPN only.
