### ISSUE TITLE
miTLS server potentially mishandle "signature_algorithms" extension given by ClientHello

### ISSUE THREAD

**Issue by oweisse-msft** [mitls/mitls-fstar#180]
According to section 4.4.2.2 (https://tools.ietf.org/html/draft-ietf-tls-tls13-21#section-4.4.2.2), the server must only use certificates with hashing algorithms provided in the "signature_algorithms" extension sent via the ClientHello. 

In a specific experiment, the server was configured with a certificate using SHA1 (mitls-fstar/data/server-ecdsa.crt), and with CA certificate using SHA256 (mitls-fstar/data/ca.crt) . The miTLS client was configured, to use "ECDSA+SHA512" (ecdsa_secp521r1_sha512), and was able to complete the handshake and send application data in both directions (no 0RTT). 

The server CertificateVerify had SignatureScheme set to ecdsa_secp521r1_sha512, and MAYBE signed the content using sha512. However, the certificate does not meet the requirements of the RFC-draft-21 section 4.4.2.2: 

> "All certificates provided by the server MUST be signed by a signature algorithm that appears in the "signature_algorithms" extension"

The important issue here is that the miTLS client should have rejected the certificate  provided by the server, as it did not math the specification sent at the ClientHello.
.

**Comment by ad-l** [comment]
This is fixed now (the certificate callbacks determines the possible signature on the server side based on the selected certificate)
