### ISSUE TITLE
miTLS server rejects a retried ClientHello which seems to be legal

### ISSUE THREAD

**Issue by oweisse-msft** [mitls/mitls-fstar#184]
OpenSSL client sends ClientHello, with KeyShare not supported by the miTLS client:
![image](https://user-images.githubusercontent.com/28742473/28948186-f50f94ba-7868-11e7-9205-8c3e81b2a8a0.png)

miTLS server replies with HelloRetry:
![image](https://user-images.githubusercontent.com/28742473/28948152-c97d74d4-7868-11e7-803f-1ededdd8c163.png)

OpenSSL client replies with an amended ClientHello:
![image](https://user-images.githubusercontent.com/28742473/28948194-033b315c-7869-11e7-9ccb-471127ac1595.png)

miTLS server emits an "illegal_parameter alert. The debug output says: "TLS| sendAlert AD_illegal_parameter (Inconsistant parameters between first and second client hello)".

While the ClientHello contains less extensions than before, it seems to conform to the requirements in section 4.1.4 of the RFC (draft 21).

**Comment by ad-l** [comment]
The new ClientHello sent by OpenSSL does not comply with the rules in 4.1.2: **the client MUST send the same ClientHello (without modification) except for key_share, early_data, cookie, pre_shared_key**
In that case extensions from the original CH are removed in the second one

**Comment by ad-l** [comment]
Fixed in OpenSSL master
