### ISSUE TITLE
Finished message

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#19]
HASH.fst:  
  Could be moved to CoreCrypto

HMAC.fst: 
  Code for the finished message
   Could be moved to CoreCrypto, once TLSConstants is partially moved there

Used only by the Handshake; need to understand the HS spec before completing this

**Comment by markulf** [comment]
We might need an idealised MAC module for finished messages at some point. Maybe part of the KeySchedule. Lets keep this issue close and lets cross that bridge when we get there.
