### ISSUE TITLE
Signatures

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#20]
Owned by Antoine, interface to X.509.
Sig.p.fst 
UntrustedCert.fst 
Cert.fst

**Comment by markulf** [comment]
not part of mitls-ver target

**Comment by s-zanella** [comment]
Now part of tls-ver and linked to CoreCrypto.
Sig disappeared, use Signature now.

**Comment by ad-l** [comment]
Shamelessly assigning Santiago. The feature is implemented but there is currently a functional bug in the verification function.

**Comment by s-zanella** [comment]
I'm on it.

**Comment by s-zanella** [comment]
This was not a bug in the signature verification function, it was a bug in an extension negotiation function in TLSExtensions.

I tracked down the problem with signature validation in TestClient to the signature_algorithms extension in the ClientHello not being passed on to `n.n_extensions.ne_signature_algorithms`.
Signature validation works after fixing `negotiateClientExtensions` to copy the extension from ClientHello.
