### ISSUE TITLE
Stabilize verification of Range.fst

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#22]
This one dominates verification time for the whole project (currently)
Should tune it: Both on fuel parameters; and disabling some stuff (Nik)
Anything marked as (* Sanity Check *) can be commented out
Currently specialized to exclude TLS-1.3, to be improved

**Comment by s-zanella** [comment]
- [ ] Unnecessary sanity checks are now commented out.
- [ ] Fuel has been tuned for all lemmas.

Range.fst takes just 30s to verify on its own (i.e. `time make Range.fst-ver`).
When running `make tls-ver` Z3 gets confused because there are many more things in the context, and this results either in a failure or a excessively long verification time.

**Comment by sishtiaq** [comment]
File a perf issue for "make tls-ver"? Assign me to it, I fancy some perf debugging.

**Comment by s-zanella** [comment]
Unfortunately it doesn't seem to be a performance issue, but an issue with Z3 getting lost when proving something in a large context. @nikswamy suggested using the Z3 Visualizer to debug this.

**Comment by ad-l** [comment]
I think the proofs are more or less stabilized.
Please reopen if you have assertion failures in Range.

**Comment by s-zanella** [comment]
Reopening since there is still one `admit()`. The proof goes through without it.

**Comment by nikswamy** [comment]
I'm starting to see instability in Range.fst again. Hints don't seem to be helping.

e.g., with hints

(.\Range.fst(180,80-199,8)) Query succeeded in 26593 milliseconds with fuel 0 and ifuel 0

still taking a long time to verify one query. 

And worse, with hints, I'm seeing queries failing initially, and then succeeding after retrying, after taking a long time.

(.\Range.fst(255,67-264,86)) Query failed in 60157 milliseconds with fuel 0 and ifuel 2 ... retrying
(.\Range.fst(255,67-264,86)) Query succeeded in 45556 milliseconds with fuel 0 and ifuel 2
(.\Range.fst(266,29-270,27)) Query failed in 60114 milliseconds with fuel 0 and ifuel 1 ... retrying
(.\Range.fst(266,29-270,27)) Query succeeded in 31695 milliseconds with fuel 0 and ifuel 1

Range.fst changed about a week ago... wonder if that has anything to do with this verification performance regression.

**Comment by nikswamy** [comment]
FYI, it seems that a change in F* may be responsible for this. At least I can report that using F* master@18a8cd4bd5ef965be6db861bfe1aa7963d758ce6 seems to provide good verification times and stability with hint enabled.

**Comment by nikswamy** [comment]
Looks like merging dm4free with master sent Range.fst off the rails
This seems to be the first commit at which hint replay fails (no idea why, yet)
be187f14cac46e2aa5ae6acf334d661c9e77ea3f

**Comment by vkanne-msft** [comment]
@nikswamy can this be closed now ?
