### ISSUE TITLE
Add CI support on all platforms.

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#27]
Linux, OS X, Windows.
Strider, Travis, NuBuild.

**Comment by sishtiaq** [comment]
@beurdouche's comment re running flex scenarios: 
The basic principle here is to create fresh machines running TLS servers or clients (multiple versions) and one (or more) other machine(s) that runs SmackTLS against all those.
All machines are fresh and build following fixed rules and are completely independent from the local environment.

**Comment by ad-l** [comment]
I think we do have decent CI coverage now. If you want to bring up a particular issue (e.g. tls-ver vs tls-gen) please create a specific bug report
