### ISSUE TITLE
interop

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#29]
@s-zanella @sishtiaq @karthikbhargavan 
Interop testing: Schannel #53, OpenSSL, NSS, TLS1.3JS.

**Comment by ad-l** [comment]
Schannel, openssl, NSS are all tested. What we need now is scripts for automated testing

**Comment by beurdouche** [comment]
@ad-l : this is in progress...

**Comment by sishtiaq** [comment]
then don't close the CI Issue!
