### ISSUE TITLE
Crypto.dfy + miTLS.fst interops

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#33]
Easy: compile F* to F#, Dafny to C#. Done

Better: We work on a compilation pipeline from a miniML intermediate language to C++ 
miniML is designed to be an easy compilation target for F* and Dafny
We compile both to miniML and interop natively in C++

**Comment by vkanne-msft** [comment]
This is duplicating #112. Closing this to avoid confusion.
