### ISSUE TITLE
Unit test for StatefulLHAE and StreamAE

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#34]
Unit test for StatefulLHAE and StreamAE, running and verifying (4 goals with AES_GCM first)
    a. Pick some content for bulk encryption, facilitating comparisons e.g. with OpenSSL; write the corresponding SamplePlain module for confidentiality and integrity (simplified from DataStream--Content--LHAEPlain/StreamPlain), validating our AE code is not TLS specific [Santiago]
    b. Set up interop tests using test vectors [started by Jonathan]
    c. Widen support to other AE methods, notably MEE and CCM
    d. Start collecting performance numbers
This links to work on implementing/verifying efficient AES_GCM code.

**Comment by ad-l** [comment]
We have record tests and test client/server now. Closing

**Comment by markulf** [comment]
Seems too good to be true. Maybe reopen issues for some of the sub-goals a)-d).
