### ISSUE TITLE
Complete and test top-level API in TLS.fst

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#39]
Top-level interface to sub-protocol. Owned by @nikswamy @fournet 
Propagate the style from TLSOutline.fst.

**Comment by s-zanella** [comment]
Testing interoperability between client and server (and OpenSSL) through the `mitls.exe` command-line tool via #76 is a pre-requisite. We should then test the following at a minimum

- [ ] Test that we can send and handle `close_notify` correctly
- [ ] Test fragmentation by transferring a large file

**Comment by ad-l** [comment]
The top level API is now tested; see test/TestAPI.fst (invoked through mitls.exe -tlsapi)

**Comment by s-zanella** [comment]
Reopening to track the progress of tests for 1.2 and the two bullets above. 
Currently TestAPI tests only the API for 1.3.

**Comment by vkanne-msft** [comment]
@s-zanella  i guess this can be close now right ?

**Comment by s-zanella** [comment]
The API-level tests for TLS 1.2 are done, but I'm not sure about the two bullets above. 
I don't think we have tested fragmentation or large file transfers.

**Comment by vkanne-msft** [comment]
Design and tested but not verified. Verification not be finished in M1.

**Comment by BarryBo** [comment]
Closing this old work item.  Top-level TLS.fst is working nicely.
