### ISSUE TITLE
Multiplexing among record ciphersuites 

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#49]
- [ ] restore LHAE.fst file, it's currently not included in the 
- [ ] rewrite StatefulLHAE to multiplex among the ciphers 
- [x] Adapt 1.2 AE to monotonic style of 1.3 
- [x] Multiplex between 1.2 and 1.3 in StAE
- [x] Test StAE with 1.2 and 1.3 record ciphers

**Comment by s-zanella** [comment]
Top priority is to make StAE support AES-GCM for TLS 1.2 and 1.3

**Comment by s-zanella** [comment]
StAE now multiplexes between TLS 1.2 (StatefulLHAE) and 1.3 (StreamAE).
I also updated StatefulLHAE and AEAD_GCM to use monotonic counters and logs.

The changes 87e0d891c0092b30917ce9d9d4b636b578959b43 ... 22ccc1578e86448fca2875572f4d90a96aa980a4 fully verify (i.e. tls-ver passes up to StAE) against 96893891d2b8a0a7c9949833ffa1f020c06f0bf2.

I tried running the test client and server apps and the 1.2 client works fine.
For the TLS 1.2 and 1.3 server, when ran either against OpenSSL or a miTLS client, I get an error I don't remember seeing before:
```
 Starting test TLS server...
Received HS(ClientHello)
Logged message = Parsed message? yes
Fatal error: exception Failure("no supported group or key share extension found")
```
I checked and this was also the case in master before my changes. Any thoughts?

**Comment by nikswamy** [comment]
This is awesome! Esp. the upgrade to monotonic counters and logs
> StAE now multiplexes between TLS 1.2 (StatefulLHAE) and 1.3 (StreamAE).
>  I also updated StatefulLHAE and AEAD_GCM to use monotonic counters and logs.
> 
> The changes  87e0d89  ...  22ccc15  fully verify (i.e. tls-ver passes up to StAE) against  9689389 

.

**Comment by s-zanella** [comment]
The MonotoneSeq library makes it a lot easier!

**Comment by s-zanella** [comment]
StAE now multiplexes among 1.2 and 1.3 ciphersuites and uses monotonic references.
The test clients and servers interoperate between themselves, and the 1.2 client and server interoperate with OpenSSL.

The remaining two bullets in this issue aren't part of Milestone #0 and do not really make much sense until we have another ciphersuite to multiplex among (e.g. MEE).

**Comment by vkanne-msft** [comment]
Create issue #90 for the remaining two items. You can go ahead and close this one.
