### ISSUE TITLE
Build on OSX is broken by default (libsqlite3 and libcrypto)

### ISSUE THREAD

**Issue by beurdouche** [mitls/mitls-fstar#5]
[build] [documentation]
You might have trouble building `miTLS*` under OSX because of `openssl` or `sqlite3`.
This is because OSX ship with old versions of those libraries by default.

This will cause errors similar to this one when building `miTLS*`:
```
Undefined symbols for architecture x86_64:
  "_sqlite3_enable_load_extension", referenced from:
      _caml_sqlite3_enable_load_extension in libsqlite3_stubs.a(sqlite3_stubs.o)
     (maybe you meant: _caml_sqlite3_enable_load_extension)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
ocamlopt.opt returned with exit code 2
```

You might want to install newer versions using `homebrew` to solve this problem, but be aware that it will not be linked by default. When installing `ocaml-sqlite3` using `opam`, please make sure to reference the correct library or by default it will use the system one. 

In order to do that please set the `PKG_CONFIG_PATH` variable properly before doing `opam install sqlite3`: 
```
export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig:$PKG_CONFIG_PATH"
```
This should be enough to reference and build against the correct `sqlite3` library and solve the problem.
Note that you might have similar problems with `openssl`, as we use it for some cryptographic primitives.

**Comment by msprotz** [comment]
Yeah this should definitely go into INSTALL.md; I'll do it

**Comment by msprotz** [comment]
And this is the right solution, too

**Comment by s-zanella** [comment]
Assigning @beurdouche. Can you update INSTALL.md with your solution?

**Comment by msprotz** [comment]
I did it.
