### ISSUE TITLE
Specify how cURL will call miTLS

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#54]
Short document needed to specify work. 
Might be two ways (short-term and long-term) to do the work.

**Comment by BarryBo** [comment]
Done.  See [Design Note 3](https://microsoft-my.sharepoint.com/personal/nswamy_microsoft_com/_layouts/OneNote.aspx?id=%2Fpersonal%2Fnswamy_microsoft_com%2FDocuments%2FIMPS&wd=target%28docs.one%7C0DC2DD71-48CA-4415-9602-D27F935B3B90%2FDesign%20Note%203%20-%20Hosting%20miTLS%20in%20C%20applications%20%7CB9D52831-0028-463F-82EE-20D7DDBC68FE%2F%29
) in the IMPS OneNote
