### ISSUE TITLE
Investigate cURL APIs

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#55]
In order to get cURL to call miTLS instead of, say, OpenSSL. 
Might involve OCaml--C and C--OCaml wrapping.

**Comment by BarryBo** [comment]
Work is in progress - see the "ffi" branch in mitls.

**Comment by BarryBo** [comment]
Curl is working, checked into mitls master.  Design Note 5 is a work-in-progress doc that describes what Cedric, Jonathan and I have put together, on a longer-term API design for miTLS.
