### ISSUE TITLE
Prune 3rdparty

### ISSUE THREAD

**Issue by markulf** [mitls/mitls-fstar#56]
We should remove unused binaries and licences from the 3rdparty directory. It would be nice to prune them from the history too, to make .git lighter.

Binaries that we do use should be moved to a submodule repo, like we did with OpenSSL libraries in https://github.com/FStarLang/3rdparty.

**Comment by s-zanella** [comment]
We don't rely anymore on 3rdparty.
We should clean up the VS projects, Makefiles and scripts that reference 3rdparty and remove it altogether.

**Comment by ad-l** [comment]
The deed is done. Good luck with your local index pains.
