### ISSUE TITLE
Handling overflows in sequence number and AEAD_GCM counter

### ISSUE THREAD

**Issue by markulf** [mitls/mitls-fstar#58]
All bets are off when the sequence number overflows and an IV is used twice for encrypting in GCM, so we should reflect this by not idealizing AEAD_GCM after so many encryptions. Currently AEAD_GCM checks for overflows and silently wraps back to 0, while StatefulLHAE (that calls AEAD_GCM) ignores overflows. 

This issue is a place to discuss what we should do and document our choices.

This is also related to not being able to extract big  int  constants.
FStarLang/FStar#86
https://github.com/mitls/mitls-fstar/blob/master/src/tls/AEAD_GCM.fst#L46

I remember seeing progress on this, maybe close relevant issues.

**Comment by ad-l** [comment]
AFAICT the issue is addressed now
