### ISSUE TITLE
Speed up CoreCrypto tests

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#61]
Start by changing 2048 to 1024 in “rsa_gen_key 2048” “dsa_gen_key 2048” in Tests.ml.
Fix "make test" failure. 
@s-zanella

**Comment by ad-l** [comment]
Looks like this was done, thanks.

**Comment by sishtiaq** [comment]
It's still 2048!

**Comment by s-zanella** [comment]
@sishtiaq: I can do these changes quickly if you don't have time.

**Comment by sishtiaq** [comment]
No, I'm on it.

**Comment by s-zanella** [comment]
Also FStarLang/FStar@f97ee88aeae5074c127d329dd7dc42cbd9a0f076
Done.

**Comment by sishtiaq** [comment]
@s-Zanella Can you review https://github.com/FStarLang/FStar/compare/iss61?expand=1 please?

**Comment by s-zanella** [comment]
Can you generalize on key lengths? I mean, we might want to be able to substitute 512 for 1024.
I didn't check how much time Travis spends generating keys and if it's worth it, but an alternative would be to just read keys off files and don't generate keys at all.

**Comment by s-zanella** [comment]
There is also another hardcoded key length parameter in `TestDhke` that can be abstracted.

**Comment by sishtiaq** [comment]
1.Generalizing on key lengths: Do we just want a choice between certain lengths? 512, 1024 or 2048, say? Or something more general? (I'd be tempted to go with this, to deal with the normal vs. CI cases.)  
2. What's the parameter in TestDhke? The 512 one given to dh_gen_params?

**Comment by s-zanella** [comment]
1. I'd go for generality since it's free, isn't it? But the script only needs to switch between two lengths (CI vs. other).
2. Yes, the `512`.

There is another opportunity for speeding things up in `TestEcdhke` by using a faster curve, but I think we're really stretching it at this point.
