### ISSUE TITLE
remove nubuild

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#69]
@nikswamy @protz: If we want to do this, I can do it.

sishtiaq@SaminDesktop /cygdrive/e/mitls-fstar
$ find . -name "Makefile"| xargs grep -Hsni nubuild
./.fstar/examples/low-star/Makefile:3:include $(FSTAR_HOME)/src/gmake/nubuild.mk
./.fstar/examples/relational/Makefile:8:include $(FSTAR_HOME)/src/gmake/nubuild.mk
./.fstar/lib/Makefile:3:include $(FSTAR_HOME)/src/gmake/nubuild.mk
./.fstar/ulib/Makefile:3:include $(FSTAR_HOME)/src/gmake/nubuild.mk
./src/tls/Makefile:15:# When using NuBuild, FStar must be located within the source tree.
./src/tls/Makefile:56:# ----------------------- NuBuild integration -------------------------
./src/tls/Makefile:57:NUBUILD_HOME=../../.nubuild
./src/tls/Makefile:58:NUBUILD=$(NUBUILD_HOME)/bin/NuBuild.exe
./src/tls/Makefile:59:ifdef USE_NUBUILD
./src/tls/Makefile:60:FSTAR_OR_NUBUILD=$(NUBUILD) $(NUBUILDFLAGS) FStarVerify $(FSTARFLAGS)
./src/tls/Makefile:62:FSTAR_OR_NUBUILD=$(FSTAR)
./src/tls/Makefile:188: $(FSTAR_OR_NUBUILD) $(VERFLAGS) --lax \
./src/tls/Makefile:195: $(FSTAR_OR_NUBUILD) $(VERFLAGS) \
./src/tls/Makefile:201: $(FSTAR_OR_NUBUILD) $(VERFLAGS) \
./src/tls/Makefile:224: $(FSTAR_OR_NUBUILD) $(VERFLAGS) \
./src/tls/Makefile:231: $(FSTAR_OR_NUBUILD) $(VERFLAGS) \

**Comment by msprotz** [comment]
Ok I'll wait to see what the final conclusion is -- had a chat about it yesterday with Bryan. We still need to investigate to understand why it's taking to so long.

Seems like we're getting a fraction of the parallelism we ought to get.

**Comment by sishtiaq** [comment]
https://github.com/mitls/mitls-fstar/commit/b5a102b7e3cff593da0f55df720843770ea61563 removes it from mitls; 
https://github.com/FStarLang/FStar/pull/823 removes it from FStar.
