### ISSUE TITLE
Issues in porting the hasEq change to mitls-fstar

### ISSUE THREAD

**Issue by aseemr** [mitls/mitls-fstar#70]
Issues in porting mitls to hasEq  (https://github.com/FStarLang/FStar/issues/510). Can be reproduced in has_eq_impl branch of mitls-fstar, with has_eq_impl branch of F*. Files not listed below verify.

Details of `hasEq` design and implementation are here: https://github.com/FStarLang/FStar/wiki/Deriving-hasEq-predicate-for-inductive-types,-and-types-of-equalities-in-F*.

- [ ] Not really a regression issue, but adding here for tracking purposes. Use reserved prefix 'uu__' for mangling record field names and then remove the temporary fix here: https://github.com/FStarLang/FStar/commit/107e642ec0a87c1f0e7938cbbb906ebfe252c030.

- [ ] TLSConstants.fst:parseCipherSuiteAux fails to verify with Unknown assertion failed.

- [ ] Nonce.fst needs `=` for `bytes`. In F*, `bytes` are sequences, and don't have the `=` operator, as they have a function inside. I have defined an equality function `eq` in FStar.Seq.fst. One solution to fix mitls code, is to replace all instances of `=`on `bytes` with FStar.Seq.eq, and then define `eq` in Seq.ml to be '=' on ml sequences.

- [ ] Cert.fst, same issue as Nonce.fst, needs `=` for bytes.

- [ ] Signature.fst needs `=` for type `alg`, which has a function in it, type `bytes`, which can fixed as above, and type `pubkey` which needs `=` on references. Perhaps we should assume equality on references ?

- [x] Range.fst, Unknown assertion failed for target_length and target_length_converges.

- [x] Alert.fst:parse, Unknown assertion failed.

- [x] StreamPlain.fst:scan, Unknown assertion failed.

- [ ] StreamAE.fst, 6 errors of same kind, subtyping failure between a match ... type (related to `ctr`) and `int`.

- [ ] MasterSecret.fst, I had to assume `hasEq` for `AE.id`, that's also related to `bytes`, I think.

- [ ] Encode.fst, failed to verify implicit errors.

- [x] StatefulLHAE.fst, Unknown assertion failed.

- [ ] Enc.fst, subtyping error in enc_int.

- [ ] HandshakeMessages.fst, StAE.fst, Unknown assertion failures.

- [ ] HSCrypto.fst, subtyping failure hkdf_expand_label.

- [ ] TLSPRF.fst, subtyping failure in prf_hashed.

- [ ] PRF.fst, subtyping failure in `type derived`.

- [ ] HandshakeLog.fst, subtyping failures.

- [ ] KeySchedule.fst, Handshake.fst, ConnInvariant.fst, TLS.fst -- TBD

**Comment by s-zanella** [comment]
Some of the subtyping errors come from the failure to typecheck code like this:
```F#
assume type t: #a:eqtype -> a -> Type0
let foo (#a:eqtype) (x:a) (y:a) (vx:t x) (vy:t y) : Tot (t y) = 
  if x = y then vx else vy
```
Presumably this should type check?

**Comment by nikswamy** [comment]
thanks for the minimal example. Aseem and I have been discussing this ... it's on my plate to figure out why code like this fails to verify in this branch.

**Comment by aseemr** [comment]
Thanks for looking into the failures @s-zanella. But this example verifies for me in the has_eq_impl branch. You are right though many subtyping failures looked to be this kind.

**Comment by s-zanella** [comment]
I tried again and it doesn't verify for me:
```F#
module M

assume type t: #a:eqtype -> a -> Type0
let foo (#a:eqtype) (x:a) (y:a) (vx:t x) (vy:t y) : Tot (t y) =
  if x = y then vx else vy
```
```
$ fstar.exe --universes M.fst
Checking tc_trivial_guard for:

(Tm_fvar:Prims.l_imp (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_name:a)) (Tm_fvar:Prims.l_Forall (fun a -> {:pattern (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0))} (Tm_fvar:Prims.l_imp (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_bvar:a!0)) (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0))))))) (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_name:a)))))

Checking haseq soundness for:(Tm_fvar:Prims.l_imp (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_name:a)) (Tm_fvar:Prims.l_Forall (fun a -> {:pattern (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0))} (Tm_fvar:Prims.l_imp (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_bvar:a!0)) (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0))))))) (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_name:a)))))
Checking tc_assume for axiom:(Tm_fvar:Prims.l_Forall (fun a -> {:pattern (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0))} (Tm_fvar:Prims.l_imp (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_bvar:a!0)) (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0)))))
Skipping this type since noeq:FStar.Heap.aref
M.fst(5,16-5,18): Subtyping check failed; expected type (?15494 Tm_name:a Tm_name:x Tm_name:y Tm_name:vx Tm_name:vy); got type (Tm_fvar:M.t Tm_name:x)
Error: 1 errors were reported (see above)
```

**Comment by aseemr** [comment]
This is strange:

aseemr@ASRAST-LT1 ~/FStar
$ git branch
* has_eq_impl
  master

aseemr@ASRAST-LT1 ~/FStar
$ git status
On branch has_eq_impl
Your branch is up-to-date with 'origin/has_eq_impl'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        univt.fst

nothing added to commit but untracked files present (use "git add" to track)

aseemr@ASRAST-LT1 ~/FStar
$ git pull
Already up-to-date.

aseemr@ASRAST-LT1 ~/FStar
$ fstar.exe --universes univt.fst
Checking tc_trivial_guard for:

(Tm_fvar:Prims.l_imp (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_name:a)) (Tm_fvar:Prims.l_Forall (fun a -> {:pattern (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0))} (Tm_fvar:Prims.l_imp (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_bvar:a!0)) (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0))))))) (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_name:a)))))

Checking haseq soundness for:(Tm_fvar:Prims.l_imp (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_name:a)) (Tm_fvar:Prims.l_Forall (fun a -> {:pattern (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0))} (Tm_fvar:Prims.l_imp (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_bvar:a!0)) (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0))))))) (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_name:a)))))
Checking tc_assume for axiom:(Tm_fvar:Prims.l_Forall (fun a -> {:pattern (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0))} (Tm_fvar:Prims.l_imp (Tm_fvar:Prims.l_and Tm_fvar:Prims.l_True (Tm_fvar:Prims.hasEq Tm_bvar:a!0)) (Tm_fvar:Prims.hasEq (Tm_fvar:FStar.Heap.ref Tm_bvar:a!0)))))
Skipping this type since noeq:FStar.Heap.aref
Verifying module: Univt
All verification conditions discharged successfully

aseemr@ASRAST-LT1 ~/FStar
$ cat univt.fst
module Univt

assume type t: #a:eqtype -> a -> Type0
let foo (#a:eqtype) (x:a) (y:a) (vx:t x) (vy:t y) : Tot (t y) =
  if x = y then vx else vy

aseemr@ASRAST-LT1 ~/FStar
$

**Comment by aseemr** [comment]
@nikswamy, did this commit https://github.com/mitls/mitls-fstar/commit/aafacbb7d72de83748b99d7f5a287b0d72838484 fix Range.fst and Alert.fst ?

**Comment by s-zanella** [comment]
@aseemr: I don't think so. It couldn't because it hasn't been merged into the has_eq_impl branch.
I marked those as fixed because they were passing for me after updating the OCaml snapshot. So, it's either that or some commit in has_eq_impl that fixed those. Aren't they typechecking for you now?

**Comment by aseemr** [comment]
@s-zanella, they (and a couple more) verify on my desktop too.

**Comment by aseemr** [comment]
Merged into main, closing.
