### ISSUE TITLE
Complete Handshake API implementation for TLS1.3 

### ISSUE THREAD

**Issue by vkanne-msft** [mitls/mitls-fstar#72]
Handshake.fst has fake implementations that we would like to complete.

**Comment by s-zanella** [comment]
This should be complete, but there is an unidentified issue with the implementation.

@ad-l and @prosecco mentioned the state machine not transitioning and getting stuck after processing some messages. They will look into this.

**Comment by vkanne-msft** [comment]
Can we log the bug ( you did mention it is unidentified but hoping we can still describe it ) and close this one ?

**Comment by s-zanella** [comment]
@ad-l just mentioned he managed to get up to ServerFinished using the top-level API.
@ad-l, can you comment?

**Comment by ad-l** [comment]
I fixed the remaining bugs today; the implementation should be complete for 1-RTT
