### ISSUE TITLE
Specify, verify, and test HKDF functions

### ISSUE THREAD

**Issue by s-zanella** [mitls/mitls-fstar#81]
- [x] Specify HKDF-Extract and HKDF-Expand as per [RFC5869](https://tools.ietf.org/html/rfc5869) -- fix `hkdf_expand_int`
- [x] Fully type check the implementation and add the module to VERIFY in the Makefile
- [x] Test using the test vectors from the RFC
- [x] Move the functions to a separate file for an HKDF module (see #18)

We will eventually switch to the low-fstar implementations.

**Comment by s-zanella** [comment]
Closed via 003d4b9.
`hkdf_expand_label` is untested, but it's a simple wrapper for `hkdf_expand`.

**Comment by ad-l** [comment]
KeySchedule now uses HKDF.hkdf_expand_label 
HSCrypto is completely gone

**Comment by s-zanella** [comment]
I'm confused. That was already the case in 003d4b9505f1cf83d5e4c27a0165bc13ffea3198.
