### ISSUE TITLE
General-purpose database implementation

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#9]
DHDB:
Uses DB for storing DH parameters
Sign-off criteria: 
  Ocaml tests to read and write DH parameters via the DB interface beneath it
  F\* program extracted to Ocaml exercising the same functionality

DB: 
Uses sqlite3
Used to work with SQLite3 from F# (?)

We need better tests, and existing tests are broken.

**Comment by msprotz** [comment]
@s-zanella has the expertise
@ad-l says it doesn't work and is broken

**Comment by msprotz** [comment]
we need a repro case (but is it more than just running "make test" in that directory?)

**Comment by s-zanella** [comment]
Postponing this since it isn't essential for Milestone #1

**Comment by s-zanella** [comment]
Bumped the priority of the issue,
We need this to implement 0-RTT in TLS 1.3.

**Comment by BarryBo** [comment]
Closing.  We broke our dependency on databases and global state.
