### ISSUE TITLE
Logging for Debugging

### ISSUE THREAD

**Issue by vkanne-msft** [mitls/mitls-fstar#93]
The current miTLS contains quite a bit of printf()-based logging.  That will affect performance, and makes hosting miTLS in external apps challenging, as those apps expect stdout/stderr to be theirs, not polluted with some subcomponent’s output.

We will need to review the existing log statements and differentiate between debug and production builds.

**Comment by s-zanella** [comment]
We now have some basic support for debugging, using flags that can be set to `false` for production code.
We need a more convenient way of disabling debug information entirely, in addition to a per-module flag.

**Comment by BarryBo** [comment]
Closing.  We now have good logging in the retail build, via Windows ETW, OutputDebugString(), printf(), or host callbacks.
